"""Check or regenerate Direction C report figures.

By default this script does not regenerate any plots. It verifies that the
existing Direction C images referenced by ``direction_C_nonfourier_report.tex``
are present and rewrites the LaTeX caption snippets under ``report_images/``.

Use ``--regenerate`` only when the underlying simulations should be rerun:

    MPLCONFIGDIR=/tmp/matplotlib python report_images/generate_direction_c_report_images.py --regenerate

For a smaller rerun of the application and sweep studies:

    MPLCONFIGDIR=/tmp/matplotlib python report_images/generate_direction_c_report_images.py --regenerate --quick
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "report_images"

FIGURES = [
    ROOT / "test_plots/direction_C_nonfourier_phase_change/hyperbolic_stefan_apparent_capacity.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/fractional_stefan_apparent_capacity.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/expansion_studies/hyperbolic_relaxation_balance.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/expansion_studies/fractional_memory_convergence.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/expansion_studies/mushy_zone_capacity_coupling.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/applications/pulsed_laser_melting.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/applications/cryosurgery_freezing.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/applications/moving_scan_melt_pool.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/applications/dual_pulse_remelting.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/applications/rapid_solidification_quench.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/applications/buried_hot_inclusion_relaxation.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/applications/pulsed_laser_melting_diagnostics.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/applications/cryosurgery_freezing_diagnostics.png",
    ROOT / "test_plots/direction_C_nonfourier_phase_change/sweeps/parameter_sweep_suite.png",
]

CAPTIONS = {
    "direction_c_verification": (
        "Manufactured Direction C verification fields for hyperbolic and fractional "
        "apparent-capacity Stefan problems. The left panel uses the Cattaneo "
        "relaxation model with a traveling $\\tanh$ interface; the right panel uses "
        "a Caputo fractional-time model with a smooth moving front. Both figures are "
        "generated by the existing Direction C verification workflow and compare the "
        "finite-volume field against manufactured exact data.",
        "direction-c-verification",
    ),
    "direction_c_relaxation_balance": (
        "Relaxation-aware hyperbolic Stefan diagnostics. The figure summarizes how "
        "the Cattaneo relaxation time $\\tau$ changes the relative balance of wave, "
        "storage, and diffusion terms, and records solver-backed manufactured errors "
        "and convergence metadata across stable relaxation-time values.",
        "direction-c-relaxation-balance",
    ),
    "direction_c_fractional_memory": (
        "Fractional-memory Stefan diagnostics. The plot shows how the Caputo/L1 "
        "history weights retain past thermal states, how observed temporal order "
        "tracks the expected $2-\\beta$ behavior, and how short-memory truncation "
        "trades accuracy for reduced history cost.",
        "direction-c-fractional-memory",
    ),
    "direction_c_mushy_capacity": (
        "Latent-heat and mushy-zone stiffness diagnostics. Apparent heat capacity "
        "replaces a sharp latent-heat jump with a finite temperature interval, but "
        "narrowing that interval creates a large capacity spike that directly affects "
        "nonlinear convergence and interface dynamics.",
        "direction-c-mushy-capacity",
    ),
    "direction_c_application_gallery": (
        "Representative Direction C application studies. Pulsed laser melting, "
        "cryosurgery freezing, additive-manufacturing-like scanning, dual-pulse "
        "remelting, rapid quenching, and buried-inclusion relaxation exercise the "
        "same non-Fourier apparent-capacity machinery under physically distinct "
        "forcing and boundary conditions.",
        "direction-c-application-gallery",
    ),
    "direction_c_diagnostics_gallery": (
        "Application-level nonlinear and energy diagnostics. The dashboards expose "
        "Picard/Anderson iteration counts, normalized nonlinear residuals, "
        "apparent-capacity extrema, sensible and latent enthalpy histories, and "
        "energy-closure residuals for flux-driven and cooling-driven phase-change "
        "scenarios.",
        "direction-c-diagnostics-gallery",
    ),
    "direction_c_parameter_suite": (
        "Direction C parameter-sweep suite. The step-8 matrix collects manufactured "
        "errors, nonlinear iteration costs, failed-step counts, stiffness/residual "
        "behavior, and coverage by swept parameter axis across hyperbolic and "
        "fractional Stefan variants.",
        "direction-c-parameter-suite",
    ),
}


def write_captions() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, (text, label) in CAPTIONS.items():
        (OUT / f"{name}.caption.tex").write_text(
            f"\\caption{{{text}}}\n\\label{{fig:{label}}}\n",
            encoding="utf-8",
        )


def check_figures() -> None:
    missing = [path for path in FIGURES if not path.exists()]
    if missing:
        listing = "\n".join(f"  - {path.relative_to(ROOT)}" for path in missing)
        raise SystemExit(f"Missing Direction C report figures:\n{listing}")


def regenerate(quick: bool) -> None:
    app_cmd = [sys.executable, str(ROOT / "direction_c_applications.py")]
    sweep_cmd = [sys.executable, str(ROOT / "direction_c_studies.py")]
    if quick:
        app_cmd.append("--quick")
        sweep_cmd.append("--quick")
    subprocess.run(app_cmd, cwd=ROOT, check=True)
    subprocess.run(sweep_cmd, cwd=ROOT, check=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Check or regenerate Direction C report figures.")
    parser.add_argument("--regenerate", action="store_true", help="rerun Direction C plot-producing scripts")
    parser.add_argument("--quick", action="store_true", help="use quick mode when regenerating")
    args = parser.parse_args()

    if args.regenerate:
        regenerate(quick=args.quick)
    write_captions()
    check_figures()
    print(f"Direction C report figures available: {len(FIGURES)}")
    print(f"Caption snippets written to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
